apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-mcp-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/plex-mcp-server.git
    targetRevision: HEAD
    path: k8s/base
    # Kustomize configuration if needed
    # kustomize:
    #   images:
    #   - name: ${IMAGE_NAME}
    #     newName: your-dockerhub-username/plex-mcp-server
    #     newTag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: plex-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true