apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-mcp-server
  labels:
    app: plex-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex-mcp-server
  template:
    metadata:
      labels:
        app: plex-mcp-server
    spec:
      containers:
      - name: plex-mcp-server
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: PLEX_URL
          valueFrom:
            secretKeyRef:
              name: plex-mcp-secrets
              key: plex-url
        - name: PLEX_TOKEN
          valueFrom:
            secretKeyRef:
              name: plex-mcp-secrets
              key: plex-token
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3001"
        - name: TRANSPORT
          value: "sse"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5