apiVersion: v1
kind: Service
metadata:
  name: plex-mcp-server
  labels:
    app: plex-mcp-server
spec:
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: plex-mcp-server